### ISSUE TITLE
Resize images

### ISSUE THREAD

**Issue by jangrewe** [xHain-hackspace/xHain-website#13]
Hi, there's a 28MB photo embedded on your homepage, and of course also used as the featured image of the article it links to. I think 4000x6000 px is a bit of an overkill...

https://x-hain.de/images/birthday.jpg
https://x-hain.de/de/2017/05/ein-ganzes-jahr-ist-rum.-zeit-f%C3%BCr-party/

**Comment by Samwise007** [comment]
Ups, you're right. Sorry. Resized to 400x600
