### ISSUE TITLE
Calendar: Sync with user devices

### ISSUE THREAD

**Issue by pantierra** [xHain-hackspace/xhain-website#65]
**Idea:** allow people to subscribe to the calendar by adding a link on the website's calendar.

This is a follow up to #45: Include CalDAV link to the calendar

**Comment by pantierra** [comment]
Started looking into this briefly:

* An `ics` file doesn't seem to be suitable as it imports only the state of a given time, and is not able to sync with updates that are constantly happening in the calendar. 
* CalDAV could work, but seems to need authentication and access to the following endpoint:
  - `https://files.x-hain.de/remote.php/dav`
  - `https://files.x-hain.de/remote.php/dav/principals/users/USERNAME/` (for MacOS)

We need to find a way to subscribe to the calendar without authentication and then add the link.

**Comment by pantierra** [comment]
Nevermind. Found a working public link and will add it in a PR.

**Comment by xamanu** [comment]
Done.
